/**
 * SQL 方言检测器 — 基于启发式计分规则
 *
 * 正分 → PostgreSQL 特征
 * 负分 → MySQL 特征
 * 零分 → Unknown
 */

import { lex, type Token, TokenType } from './tokenizer'

export type DetectedDialect = 'mysql' | 'postgresql' | 'unknown'

/**
 * 从原始 SQL 文本检测方言
 */
export function detectDialect(sql: string): DetectedDialect {
  const tokens = lex(sql)
  return detectDialectFromTokens(tokens)
}

/**
 * 从 Token 流检测方言
 */
export function detectDialectFromTokens(tokens: Token[]): DetectedDialect {
  let score = 0

  // 提取所有 KEYWORD token 的值（用于批量检测）
  const keywords = new Set<string>()
  const allValues: string[] = []
  let hasBacktickId = false
  let hasDoubleQuoteId = false
  let hasEngine = false
  let insideCreateTable = false

  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i]!

    // 跟踪引号风格
    if (t.type === TokenType.BACKTICK_ID) {
      hasBacktickId = true
    }
    if (t.type === TokenType.DOUBLEQUOTE_ID) {
      hasDoubleQuoteId = true
    }

    if (t.type === TokenType.KEYWORD) {
      keywords.add(t.value)
      allValues.push(t.value)
    } else {
      allValues.push(t.value)
    }

    // 跟踪是否在 CREATE TABLE 内部
    if (t.type === TokenType.KEYWORD && t.value === 'CREATE') {
      // 检查后面的token
      if (tokens[i + 1]?.value === 'TABLE' || tokens[i + 1]?.value === 'OR_REPLACE') {
        insideCreateTable = true
      }
    }
    if (t.type === TokenType.SYMBOL && t.value === ';') {
      insideCreateTable = false
    }

    // ENGINE= 只在 CREATE TABLE 外部选项区出现
    if (t.type === TokenType.KEYWORD && t.value === 'ENGINE') {
      hasEngine = true
    }
  }

  // ===== PostgreSQL 特征（正分） =====

  // GENERATED ALWAYS AS IDENTITY / GENERATED BY DEFAULT AS IDENTITY (weight +3)
  if (keywords.has('GENERATED_ALWAYS') || keywords.has('GENERATED_BY_DEFAULT') || keywords.has('AS_IDENTITY')) {
    score += 3
  }

  // SERIAL / BIGSERIAL / SMALLSERIAL (weight +3)
  if (keywords.has('SERIAL') || keywords.has('BIGSERIAL') || keywords.has('SMALLSERIAL')) {
    score += 3
  }

  // :: 类型转换 (weight +2)
  for (let i = 0; i < tokens.length; i++) {
    if (tokens[i]!.type === TokenType.SYMBOL && tokens[i]!.value === '::') {
      score += 2
      break
    }
  }

  // DOUBLE PRECISION (weight +1)
  if (keywords.has('DOUBLE_PRECISION')) {
    score += 1
  }

  // 双引号标识符 + 无 ENGINE 子句 (weight +2)
  if (hasDoubleQuoteId && !hasEngine) {
    score += 2
  }

  // 纯双引号标识符（没有任何反引号）(weight +1)
  if (hasDoubleQuoteId && !hasBacktickId) {
    score += 1
  }

  // CREATE SCHEMA (weight +1)
  const allText = allValues.join(' ')
  if (/\bCREATE\s+SCHEMA\b/i.test(allText)) {
    score += 1
  }

  // COMMENT ON TABLE/COLUMN (weight +1)
  if (keywords.has('COMMENT') && /\bCOMMENT\s+ON\b/i.test(allText)) {
    score += 1
  }

  // PostgreSQL 特有类型
  if (keywords.has('JSONB') || keywords.has('BYTEA') || keywords.has('INET') ||
      keywords.has('CIDR') || keywords.has('MACADDR') || keywords.has('TIMESTAMPTZ')) {
    score += 2
  }

  // BOOLEAN 作为类型（MySQL 中 BOOLEAN 是 TINYINT(1) 别名较少见）
  if (keywords.has('BOOLEAN') || keywords.has('BOOL')) {
    score += 0 // 中性，不加减分
  }

  // ===== MySQL 特征（负分） =====

  // 反引号标识符 (weight -2)
  if (hasBacktickId) {
    score -= 2
  }

  // ENGINE= (weight -3)
  if (hasEngine) {
    score -= 3
  }

  // AUTO_INCREMENT (weight -3)
  if (keywords.has('AUTO_INCREMENT')) {
    score -= 3
  }

  // TINYINT 作为列类型 (weight -2)
  if (keywords.has('TINYINT')) {
    score -= 2
  }

  // ENUM / SET 类型 (weight -2)
  if (keywords.has('ENUM') || keywords.has('SET')) {
    score -= 2
  }

  // ON UPDATE CURRENT_TIMESTAMP (weight -1)
  if (keywords.has('ON_UPDATE')) {
    score -= 1
  }

  // CHARACTER SET / CHARSET / COLLATE 作为表选项 (weight -1)
  if (keywords.has('CHARACTER_SET') || keywords.has('DEFAULT_CHARSET') || keywords.has('DEFAULT_COLLATE')) {
    score -= 1
  }

  // MySQL 特有类型
  if (keywords.has('MEDIUMINT') || keywords.has('MEDIUMTEXT') || keywords.has('LONGTEXT') ||
      keywords.has('TINYTEXT') || keywords.has('YEAR') || keywords.has('LONGBLOB') ||
      keywords.has('MEDIUMBLOB') || keywords.has('TINYBLOB') || keywords.has('GEOMETRY')) {
    score -= 2
  }

  // UNSIGNED / ZEROFILL (weight -1)
  if (keywords.has('UNSIGNED') || keywords.has('ZEROFILL')) {
    score -= 1
  }

  // ===== 判定 =====
  if (score >= 3) return 'postgresql'
  if (score <= -3) return 'mysql'

  // 边缘情况：没有明显特征时
  if (score > 0) return 'postgresql'
  if (score < 0) return 'mysql'

  return 'unknown'
}
