/**
 * SQL 词法分析器 — 状态机驱动的通用 Tokenizer
 *
 * 将原始 SQL 文本转化为 Token 流，每个 Token 携带：
 * - type: Token 类型
 * - value: 原始文本值
 * - line / column: 1-based 位置（用于错误报告）
 */

/** Token 类型枚举 */
export const enum TokenType {
  KEYWORD = 'KEYWORD',
  IDENTIFIER = 'IDENTIFIER',
  BACKTICK_ID = 'BACKTICK_ID',
  DOUBLEQUOTE_ID = 'DOUBLEQUOTE_ID',
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  SYMBOL = 'SYMBOL',
  COMMENT_LINE = 'COMMENT_LINE',
  COMMENT_BLOCK = 'COMMENT_BLOCK',
  EOF = 'EOF',
}

/** 单个 Token */
export interface Token {
  type: TokenType
  value: string
  line: number
  column: number
}

// ===== SQL 关键字集合（大小写不敏感） =====

const KEYWORDS = new Set([
  // DDL
  'CREATE', 'TABLE', 'ALTER', 'DROP', 'TRUNCATE', 'RENAME',
  'ADD', 'COLUMN', 'MODIFY', 'CHANGE',
  'IF', 'NOT', 'EXISTS', 'OR', 'REPLACE', 'TEMPORARY', 'TEMP',
  'CONSTRAINT', 'INDEX', 'KEY', 'PRIMARY', 'FOREIGN', 'REFERENCES',
  'UNIQUE', 'FULLTEXT', 'SPATIAL', 'CHECK',
  'USING', 'BTREE', 'HASH', 'GIST', 'GIN', 'SPGIST', 'BRIN',
  'ASC', 'DESC',
  // 列约束
  'NULL', 'DEFAULT', 'AUTO_INCREMENT', 'COMMENT',
  'CHARACTER', 'CHARSET', 'COLLATE', 'UNSIGNED', 'ZEROFILL',
  'GENERATED', 'ALWAYS', 'BY', 'AS', 'IDENTITY', 'INCREMENT',
  'ON', 'UPDATE', 'CURRENT_TIMESTAMP', 'NOW', 'IS',
  'CASCADE', 'RESTRICT', 'SET', 'NO', 'ACTION',
  // 表选项
  'ENGINE', 'ROW_FORMAT', 'DYNAMIC', 'COMPACT', 'REDUNDANT', 'COMPRESSED',
  'AUTOEXTEND_SIZE', 'AVG_ROW_LENGTH', 'CHECKSUM', 'CONNECTION',
  'DATA', 'DIRECTORY', 'DELAY_KEY_WRITE', 'ENCRYPTION',
  'INSERT_METHOD', 'KEY_BLOCK_SIZE', 'MAX_ROWS', 'MIN_ROWS',
  'PACK_KEYS', 'PASSWORD', 'STATS_AUTO_RECALC', 'STATS_PERSISTENT',
  'STATS_SAMPLE_PAGES', 'TABLESPACE', 'UNION',
  // LIKE / SELECT (用于跳过 CREATE TABLE ... LIKE/AS SELECT)
  'LIKE', 'SELECT', 'FROM', 'WHERE', 'AND',
  'INHERITS', 'PARTITION', 'WITH', 'OIDS',
  // PostgreSQL
  'SERIAL', 'BIGSERIAL', 'SMALLSERIAL',
  'SCHEMA',
  // 类型关键字（也作为 KEYWORD token，解析器根据上下文区分）
  'VARCHAR', 'CHAR', 'INT', 'INTEGER', 'BIGINT', 'SMALLINT', 'MEDIUMINT', 'TINYINT',
  'TEXT', 'TINYTEXT', 'MEDIUMTEXT', 'LONGTEXT',
  'DECIMAL', 'NUMERIC', 'FLOAT', 'DOUBLE', 'REAL',
  'BOOLEAN', 'BOOL', 'BIT', 'TRUE', 'FALSE',
  'DATE', 'DATETIME', 'TIME', 'TIMESTAMP', 'TIMESTAMPTZ', 'YEAR',
  'JSON', 'JSONB', 'UUID', 'BLOB', 'LONGBLOB', 'MEDIUMBLOB', 'TINYBLOB',
  'ENUM', 'GEOMETRY', 'POINT', 'LINESTRING', 'POLYGON',
  'BYTEA', 'INTERVAL', 'INET', 'CIDR', 'MACADDR',
  'PRECISION', 'VARYING', 'WITHOUT', 'ZONE',
  'ARRAY',
])

// 复合关键字（多词组合，用于分词时合并相邻 KEYWORD）
const COMPOUND_KEYWORDS: Record<string, string> = {
  'IF NOT EXISTS': 'IF_NOT_EXISTS',
  'OR REPLACE': 'OR_REPLACE',
  'PRIMARY KEY': 'PRIMARY_KEY',
  'FOREIGN KEY': 'FOREIGN_KEY',
  'CHARACTER SET': 'CHARACTER_SET',
  'DOUBLE PRECISION': 'DOUBLE_PRECISION',
  'NOT NULL': 'NOT_NULL',
  'AUTO INCREMENT': 'AUTO_INCREMENT',
  'GENERATED ALWAYS': 'GENERATED_ALWAYS',
  'GENERATED BY DEFAULT': 'GENERATED_BY_DEFAULT',
  'AS IDENTITY': 'AS_IDENTITY',
  'DEFAULT CHARACTER SET': 'DEFAULT_CHARSET',
  'DEFAULT CHARSET': 'DEFAULT_CHARSET',
  'DEFAULT COLLATE': 'DEFAULT_COLLATE',
  'ON UPDATE': 'ON_UPDATE',
  'NO ACTION': 'NO_ACTION',
  'SET NULL': 'SET_NULL',
  'ROW FORMAT': 'ROW_FORMAT',
  'WITHOUT TIME ZONE': 'WITHOUT_TZ',
  'WITH TIME ZONE': 'WITH_TZ',
}

/** 检查字符串是否为 SQL 关键字 */
export function isKeyword(word: string): boolean {
  return KEYWORDS.has(word.toUpperCase())
}

// ===== Tokenizer 状态机 =====

export function tokenize(input: string): Token[] {
  const tokens: Token[] = []
  let pos = 0
  let line = 1
  let column = 1
  const len = input.length

  function advance(n = 1): void {
    pos += n
    column += n
  }

  function peek(offset = 0): string {
    return pos + offset < len ? input[pos + offset]! : ''
  }

  function peekAhead(n: number): string {
    return pos + n < len ? input.substring(pos, pos + n) : ''
  }

  function pushToken(type: TokenType, value: string, startLine: number, startColumn: number): void {
    tokens.push({ type, value, line: startLine, column: startColumn })
  }

  while (pos < len) {
    const ch = input[pos]!
    const startLine = line
    const startColumn = column

    // 空白字符
    if (ch === ' ' || ch === '\t' || ch === '\r') {
      advance()
      continue
    }

    // 换行
    if (ch === '\n') {
      line++
      column = 1
      advance()
      continue
    }

    // 行注释 --
    if (ch === '-' && peek(1) === '-' && (peek(2) === ' ' || peek(2) === '\t' || peek(2) === '\n' || peek(2) === '\r' || peek(2) === '' || peek(2) === '-')) {
      let value = ''
      advance(2) // skip --
      while (pos < len && input[pos] !== '\n') {
        value += input[pos]!
        advance()
      }
      pushToken(TokenType.COMMENT_LINE, value.trim(), startLine, startColumn)
      continue
    }

    // 块注释 /* ... */
    if (ch === '/' && peek(1) === '*') {
      let value = ''
      advance(2) // skip /*
      let depth = 1
      while (pos < len && depth > 0) {
        if (input[pos] === '*' && peek(1) === '/') {
          depth--
          advance(2)
        } else if (input[pos] === '/' && peek(1) === '*') {
          depth++
          value += '/*'
          advance(2)
        } else {
          if (input[pos] === '\n') { line++; column = 1 }
          value += input[pos]!
          advance()
        }
      }
      pushToken(TokenType.COMMENT_BLOCK, value.trim(), startLine, startColumn)
      continue
    }

    // 反引号标识符 `...`
    if (ch === '`') {
      let value = ''
      advance() // skip opening `
      while (pos < len) {
        const c = input[pos]!
        if (c === '`') {
          if (peek(1) === '`') {
            value += '`'
            advance(2)
          } else {
            advance() // skip closing `
            break
          }
        } else {
          if (c === '\n') { line++; column = 1 }
          value += c
          advance()
        }
      }
      pushToken(TokenType.BACKTICK_ID, value, startLine, startColumn)
      continue
    }

    // 双引号标识符 "..."
    if (ch === '"') {
      let value = ''
      advance() // skip opening "
      while (pos < len) {
        const c = input[pos]!
        if (c === '"') {
          if (peek(1) === '"') {
            value += '"'
            advance(2)
          } else {
            advance() // skip closing "
            break
          }
        } else {
          if (c === '\n') { line++; column = 1 }
          value += c
          advance()
        }
      }
      pushToken(TokenType.DOUBLEQUOTE_ID, value, startLine, startColumn)
      continue
    }

    // 单引号字符串 '...'
    if (ch === "'") {
      let value = ''
      advance() // skip opening '
      while (pos < len) {
        const c = input[pos]!
        if (c === "'") {
          if (peek(1) === "'") {
            value += "'"
            advance(2)
          } else {
            advance() // skip closing '
            break
          }
        } else {
          if (c === '\n') { line++; column = 1 }
          value += c
          advance()
        }
      }
      pushToken(TokenType.STRING, value, startLine, startColumn)
      continue
    }

    // PostgreSQL 转义字符串 E'...'
    if ((ch === 'E' || ch === 'e') && peek(1) === "'") {
      let value = ''
      advance(2) // skip E'
      while (pos < len) {
        const c = input[pos]!
        if (c === "'") {
          if (peek(1) === "'") {
            value += "'"
            advance(2)
          } else {
            advance()
            break
          }
        } else if (c === '\\' && peek(1) !== undefined) {
          // Keep escape sequences in value
          value += '\\' + peek(1)
          advance(2)
        } else {
          if (c === '\n') { line++; column = 1 }
          value += c
          advance()
        }
      }
      pushToken(TokenType.STRING, value, startLine, startColumn)
      continue
    }

    // PostgreSQL 美元引号字符串 $tag$...$tag$
    if (ch === '$') {
      // Find the tag
      let tagEnd = pos + 1
      while (tagEnd < len && input[tagEnd] !== '$') {
        tagEnd++
      }
      if (tagEnd < len) {
        const tag = input.substring(pos, tagEnd + 1) // e.g. $tag$
        // Search for matching closing tag
        let searchPos = tagEnd + 1
        while (searchPos < len) {
          if (input.substring(searchPos, searchPos + tag.length) === tag) {
            const value = input.substring(tagEnd + 1, searchPos)
            // Count newlines in the entire dollar-quoted string
            const dollarStr = input.substring(pos, searchPos + tag.length)
            for (let i = 0; i < dollarStr.length; i++) {
              if (dollarStr[i] === '\n') { line++; column = 1 }
            }
            pos = searchPos + tag.length
            column = startColumn // approximate
            pushToken(TokenType.STRING, value, startLine, startColumn)
            break
          }
          searchPos++
        }
        if (searchPos >= len) {
          // Unclosed dollar quote — treat as symbol
          pushToken(TokenType.SYMBOL, '$', startLine, startColumn)
          advance()
          continue
        }
        continue
      }
    }

    // 数字
    if ((ch >= '0' && ch <= '9') || (ch === '.' && peek(1) >= '0' && peek(1) <= '9')) {
      let value = ''
      while (pos < len && input[pos]! >= '0' && input[pos]! <= '9') {
        value += input[pos]!
        advance()
      }
      if (input[pos] === '.' && peek(1) >= '0' && peek(1) <= '9') {
        value += '.'
        advance()
        while (pos < len && input[pos]! >= '0' && input[pos]! <= '9') {
          value += input[pos]!
          advance()
        }
      }
      pushToken(TokenType.NUMBER, value, startLine, startColumn)
      continue
    }

    // 符号
    if ('(),;=.'.includes(ch)) {
      pushToken(TokenType.SYMBOL, ch, startLine, startColumn)
      advance()
      continue
    }

    // PostgreSQL 类型转换 ::
    if (ch === ':' && peek(1) === ':') {
      pushToken(TokenType.SYMBOL, '::', startLine, startColumn)
      advance(2)
      continue
    }

    // 标识符 / 关键字
    if ((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || ch === '_') {
      let value = ''
      while (pos < len) {
        const c = input[pos]!
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c === '_') {
          value += c
          advance()
        } else {
          break
        }
      }

      // 检查是否为关键字（大小写不敏感）
      if (KEYWORDS.has(value.toUpperCase())) {
        pushToken(TokenType.KEYWORD, value.toUpperCase(), startLine, startColumn)
      } else {
        pushToken(TokenType.IDENTIFIER, value, startLine, startColumn)
      }
      continue
    }

    // 未知字符 — 跳过（宽容模式）
    advance()
  }

  // 添加 EOF
  pushToken(TokenType.EOF, '', line, column)

  return tokens
}

/**
 * 合并相邻的 KEYWORD token 为复合关键字 token
 * 例如: NOT + NULL → NOT_NULL（复合关键字作为单个 KEYWORD token）
 *       DOUBLE + PRECISION → DOUBLE_PRECISION
 */
export function mergeCompoundKeywords(tokens: Token[]): Token[] {
  const result: Token[] = []
  let i = 0

  while (i < tokens.length) {
    // 尝试匹配复合关键字（2-3个连续 KEYWORD）
    let merged = false

    // 尝试 3 词组合
    if (i + 2 < tokens.length) {
      const three = `${tokens[i]!.value} ${tokens[i + 1]!.value} ${tokens[i + 2]!.value}`
      if (COMPOUND_KEYWORDS[three]) {
        result.push({
          type: TokenType.KEYWORD,
          value: COMPOUND_KEYWORDS[three]!,
          line: tokens[i]!.line,
          column: tokens[i]!.column,
        })
        i += 3
        merged = true
      }
    }

    // 尝试 2 词组合
    if (!merged && i + 1 < tokens.length) {
      const two = `${tokens[i]!.value} ${tokens[i + 1]!.value}`
      if (COMPOUND_KEYWORDS[two]) {
        result.push({
          type: TokenType.KEYWORD,
          value: COMPOUND_KEYWORDS[two]!,
          line: tokens[i]!.line,
          column: tokens[i]!.column,
        })
        i += 2
        merged = true
      }
    }

    if (!merged) {
      result.push(tokens[i]!)
      i++
    }
  }

  return result
}

/**
 * 对 token 流进行完整词法分析：tokenize + 复合关键字合并
 */
export function lex(input: string): Token[] {
  const tokens = tokenize(input)
  return mergeCompoundKeywords(tokens)
}
