import type { UnifiedTypeDefinition } from '@/types/schema'

/** 内置默认统一类型集 — 首次加载时若 common.json 中无 unified_types 则自动填充 */
export const DEFAULT_UNIFIED_TYPES: UnifiedTypeDefinition[] = [
  {
    name: 'String',
    description: '变长字符串',
    quote_default: true,
    mysql: { type: 'VARCHAR', length: 255 },
    pgsql: { type: 'VARCHAR', length: 255 },
  },
  {
    name: 'Integer',
    description: '整数',
    quote_default: false,
    mysql: { type: 'INT', length: 11 },
    pgsql: { type: 'INTEGER' },
  },
  {
    name: 'BigInt',
    description: '大整数',
    quote_default: false,
    mysql: { type: 'BIGINT', length: 20 },
    pgsql: { type: 'BIGINT' },
  },
  {
    name: 'Boolean',
    description: '布尔值',
    quote_default: false,
    mysql: { type: 'TINYINT', length: 1 },
    pgsql: { type: 'BOOLEAN' },
  },
  {
    name: 'Text',
    description: '长文本',
    quote_default: true,
    mysql: { type: 'TEXT' },
    pgsql: { type: 'TEXT' },
  },
  {
    name: 'LongText',
    description: '超长文本',
    quote_default: true,
    mysql: { type: 'LONGTEXT' },
    pgsql: { type: 'TEXT' },
  },
  {
    name: 'Decimal',
    description: '精确小数',
    quote_default: false,
    mysql: { type: 'DECIMAL', length: 10, scale: 2 },
    pgsql: { type: 'DECIMAL', length: 10, scale: 2 },
  },
  {
    name: 'Float',
    description: '单精度浮点',
    quote_default: false,
    mysql: { type: 'FLOAT' },
    pgsql: { type: 'REAL' },
  },
  {
    name: 'Double',
    description: '双精度浮点',
    quote_default: false,
    mysql: { type: 'DOUBLE' },
    pgsql: { type: 'DOUBLE PRECISION' },
  },
  {
    name: 'Date',
    description: '日期',
    quote_default: true,
    mysql: { type: 'DATE' },
    pgsql: { type: 'DATE' },
  },
  {
    name: 'DateTime',
    description: '日期时间',
    quote_default: true,
    mysql: { type: 'DATETIME' },
    pgsql: { type: 'TIMESTAMP' },
  },
  {
    name: 'Timestamp',
    description: '时间戳',
    quote_default: true,
    mysql: { type: 'TIMESTAMP' },
    pgsql: { type: 'TIMESTAMPTZ' },
  },
  {
    name: 'JSON',
    description: 'JSON 数据',
    quote_default: true,
    mysql: { type: 'JSON' },
    pgsql: { type: 'JSONB' },
  },
  {
    name: 'UUID',
    description: 'UUID',
    quote_default: true,
    mysql: { type: 'CHAR', length: 36 },
    pgsql: { type: 'UUID' },
  },
]
